<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv='Content-type' content='text/html; charset=<?php APP_CHARSET ?>' />
        <title>KumbiaPHP web &amp; App Framework</title>
        <?php Tag::css('structure'); ?>
        <?php echo Html::includeCss() ?>
    </head>
    <body>
        <nav>
            <div class="row">
                <?php echo Html::link('', 'KumbiaPHP', 'class="logo span3" title="KumbiaPHP Framework PHP MVC"'); //Html::img('kumbiaphp.png','KumbiaPHP Framework','width=183 height=50')) ?> 
                <ul class="menu">
                    <li><?php echo Html::link('caracteristicas/', 'Características') ?></li>
                    <li><?php echo Html::link('escaparate/', 'Escaparate') ?></li>
                    <li><a href="http://www.kumbiaphp.com/blog/">Blog</a></li>
                    <li><?php echo Html::link('aprender/', 'Documentación') ?></li>
                    <li><?php echo Html::link('comunidad/', 'Comunidad') ?></li>
                    <li><?php echo Html::link('descargas/', 'Descargar') ?></li>
                </ul>
            </div>
        </nav>

        <?php KumbiaPHP\View\View::content() ?>

        <?php KumbiaPHP\View\View::partial('footer') ?>

        <?php Tag::js('jquery/jquery.min', -100) ?>
        <?php echo Html::includeJs() ?>
    </body>
</html>

