<h3>Vista</h3>
<p>este es el contenido de la vista</p>
<p>Url actual: <?php echo \K2\Kernel\App::get('app.context')->getCurrentUrl() ?></p>
<p>Controlador ejecutado: <?php echo \K2\Kernel\App::get('app.context')->getCurrentController() ?>Controller</p>
<p>Ip del Cliente: <?php echo \K2\Kernel\App::get('request')->getClientIp() ?></p>
<ul>
    <li><?php echo Html::linkAction('', 'Ejemplo 1') ?></li>
    <li><?php echo Html::linkAction('saludo/Amigo', 'Ejemplo 2') ?></li>
</ul>
<hr/>
<h2>Código de la Vista</h2>
<?php highlight_file(__FILE__); ?>