<?php echo Html::img('default/kumbia.png', 'KumbiaPHP logo') ?>
<?php \KumbiaPHP\View\View::content() ?>
<h1>KumbiaPHP está listo para usarse</h1>
<p><strong>Bienvenido a KumbiaPHP Framework</strong>. El framework ya está listo para desarrollar aplicaciones web con PHP, rápida y fácilmente, sin tener que reinventar la rueda, y preocupandose por lo más importante, la lógica de su aplicación.</p>
<h2>Como empezar</h2>
<p>Puedes ver la <a href="https://github.com/manuelj555/k2/tree/master/doc#indice-de-contenidos">Documentación en linea</a> donde encontraras la sección: <a href="https://github.com/manuelj555/k2/tree/master/doc#preguntas-frecuentes">Preguntas Frecuentes</a> donde encontrarás información actualizada sobre el uso del framework, tambien puede interesarte saber sobre:</p>
<ul>
    <li><h3><a href="https://github.com/manuelj555/k2/blob/master/doc/ejemplos/scaffold.rst">¿Cómo crear un Scaffold?</a></h3></li>
    <li><h3><a href="https://github.com/manuelj555/k2/blob/master/doc/ejemplos/creando_un_modelo.rst">¿Cómo Crear un Modelo?</a></h3></li>
    <li><h3><a href="https://github.com/manuelj555/k2/blob/master/doc/servicios.rst#definiendo-un-servicio">¿Cómo crear un Servicio?</a></h3></li>
    <li><h3><a href="https://github.com/manuelj555/k2/blob/master/doc/los_modulos.rst">¿Cómo crear un Módulo en mi Aplicación?</a></h3></li>
    <li><h3><a href="https://github.com/manuelj555/k2/blob/master/doc/los_modulos.rst#instalando-modulos-de-terceros">¿Cómo Instalar un Módulo de Terceros?</a></h3></li>
</ul>