<div class="row">
    <?php echo Html::img('default/kumbia.png', 'KumbiaPHP logo') ?>
    <?php \KumbiaPHP\View\View::content() ?>
    <h1>KumbiaPHP está listo para usarse</h1>
    <p><strong>Bienvenido a KumbiaPHP Framework</strong>. El framework ya está listo para desarrollar aplicaciones web con PHP, rápida y fácilmente, sin tener que reinventar la rueda, y preocupandose por lo más importante, la lógica de su aplicación.</p>
    <h2>Como empezar</h2>
    <p>Puedes ver la <a href="https://github.com/manuelj555/k2/tree/master/doc#indice-de-contenidos">Documentación en linea</a> donde encontraras la sección: <a href="https://github.com/manuelj555/k2/tree/master/doc#preguntas-frecuentes">Preguntas Frecuentes</a> donde encontrarás información actualizada sobre el uso del framework, tambien puede interesarte saber sobre:</p>
    <ul>
        <li><h3><a href="http://wiki.kumbiaphp.com/Beta2_CRUD_en_KumbiaPHP_Framework">Creacion de CRUD(Create, Read, Update, Delete)</a></h3></li>
        <li><h3><a href="http://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Uso de modelos</a></h3></li>
        <li><h3><a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#databases.ini">Configurar conexiones a bases de datos</a></h3></li>
    </ul>
    <p>Estos son solo algunos ejemplos puedes ver más en la <a href="http://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">sección de tutoriales de la wiki</a></p>
</div>
